### ISSUE TITLE
Change all existing dependencies in toml file concurrently

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/toml-adapt#12]
Hi @StrajnarFilip,

the following feature does not work in v0.2.0. Please check it out and implement this feature which has a very high priority.

toml-adapt -path pyproject.toml -a change -dep ALL -ver X

ALL represents all dependencies, while X means that we assign default version (in case of poetry, we assign *).

**Comment by StrajnarFilip** [comment]
Should be done since the last commit.

Best regards!

**Comment by firefly-cpp** [comment]
Proposed in #13.
