### ISSUE TITLE
0.2.3: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [firefly-cpp/toml-adapt#19]
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Looks like after move toml_adapt/tests/ to tests not everything has been updated.
Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-toml-adapt-0.2.3-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-toml-adapt-0.2.3-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/toml-adapt-0.2.3
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
________________________________________________________________ ERROR collecting tests/test_toml_adapt.py _________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/toml-adapt-0.2.3/tests/test_toml_adapt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_toml_adapt.py:1: in <module>
    from toml_adapt.tests.conftest import pytest_configure
E   ModuleNotFoundError: No module named 'toml_adapt.tests'
========================================================================= short test summary info ==========================================================================
ERROR tests/test_toml_adapt.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.12s ===========================================================================
```

**Comment by firefly-cpp** [comment]
Hi @kloczek,

Thank you for your remark. You are right. Currently, no special tests exist. It is still incomplete. I can prepare one basic test (version check) ASAP.

BTW, for which distro are you building rpm?

**Comment by kloczek** [comment]
I'm working on my own distribution.
This product still is not finished so I cannot provide access to those resources.
I have now almost 4k src.rpm pacjked and +800 of those packages are python modules.
😄 
If you will have any commits to test please let me know. I'll be glad to test that.

**Comment by firefly-cpp** [comment]
@kloczek, our collaborator @StrajnarFilip developed first test case for toml-adapt package.

I would like to ask you to re-run your build scripts.
