### ISSUE TITLE
Flit issue

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/toml-adapt#29]
Changing all existing dependencies in the toml file which Flit generates is not working correctly.

Command: **toml-adapt -path pyproject.toml -a change -dep ALL -ver X**
provides the following output:

**requires = [ "numpy X", "scipy X",]**

@StrajnarFilip, Can you check out this issue?

**Comment by StrajnarFilip** [comment]
@firefly-cpp I believe I've resolved the issue
