### ISSUE TITLE
TODO: manipulate dev-dependencies

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/toml-adapt#5]
Current version does not support manipulating dev-dependencies. Thus, cli should be extended with this functionality.

**Comment by StrajnarFilip** [comment]
I will begin to work on this issue

**Comment by firefly-cpp** [comment]
Thanks @StrajnarFilip!

**Comment by firefly-cpp** [comment]
@StrajnarFilip, how is the project coming along?

**Comment by firefly-cpp** [comment]
Implemented in #9.
